app.name=JStrimix
app.version=1.0.0

# Директория для загрузки файлов
app.upload.dir=uploads

management.endpoints.web.exposure.include=*

# База данных PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=mysecretpassword
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Настройки HikariCP для работы с LOB
spring.datasource.hikari.auto-commit=false

# Настройки загрузки файлов
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB